<a href="https://colab.research.google.com/github/BatsyBoo/DS-PRAC/blob/main/PCA_do.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

 # Small example dataset: 6 samples, 3 features
X = np.array([
       [2.5, 2.4, 1.2],
       [0.5, 0.7, 0.3],
       [2.2, 2.9, 1.0],
       [1.9, 2.2, 0.8],
       [3.1, 3.0, 1.4],
       [2.3, 2.7, 1.1],
], dtype=float)

In [ ]:
X_mean = np.mean(X, axis=0)
print(X_mean)

[2.08333333 2.31666667 0.96666667]


In [ ]:
# print(X.shape[0])
vari=((X-X_mean)*(X-X_mean))/X.shape[0]
print(vari)

[[2.89351852e-02 1.15740741e-03 9.07407407e-03]
 [4.17824074e-01 4.35601852e-01 7.40740741e-02]
 [2.26851852e-03 5.67129630e-02 1.85185185e-04]
 [5.60185185e-03 2.26851852e-03 4.62962963e-03]
 [1.72268519e-01 7.78240741e-02 3.12962963e-02]
 [7.82407407e-03 2.44907407e-02 2.96296296e-03]]


In [ ]:
X_centered = X - X_mean
covariance_matrix = np.cov(X_centered, rowvar=False)
print(cov_matrix)

[[0.76166667 0.69233333 0.33133333]
 [0.69233333 0.71766667 0.29666667]
 [0.33133333 0.29666667 0.14666667]]
